// import media files

// import courses media files

import Government from "./navbars/icons/government.png";
import Corporation from "./navbars/icons/corporate.png";
import NGO from "./navbars/icons/ngo.png";
import Professional from "./navbars/icons/professional-services.png";
import Creative from "./navbars/icons/digital-services.png";
import Home from "./navbars/icons/house.png";
import Health from "./navbars/icons/doctor-patient.png";
import Educational from "./navbars/icons/online-learning.png";
import Event from "./navbars/icons/catering.png";
import Religion from "./navbars/icons/religion.png";

import Technical from "./navbars/icons/technical-support.png";

export const AllCoursesData = [
  {
    id: 8,
    category: "consumer",
    image: Health,
    title: "Personal Care Services",
    link: "/personal-care-services",
    subtitle1: "Hair Salon",
    subtitle2: "Barber Shop",
    subtitle3: "Nail Salon",
    subtitle4: "Spa and Wellness Center",
    subtitle5: "Massage Therapy",
    subtitle6: "Skincare Clinic",
    subtitle7: "Makeup Artist Services",
    subtitle8: "Personal Training and Fitness Coaching",
    subtitle9: "Yoga and Pilates Studio",
    subtitle10: "Weight Loss and Nutrition Counseling",
    subtitle11: "Chiropractic Services",
    subtitle12: "Mental Health Counseling",
    subtitle13: "Tattoo and Piercing Studio",
    subtitle14: "Aromatherapy Services",
    subtitle15: "Dental Hygiene Services",
    subtitle16: "Reflexology Services",
    subtitle17: "Life Coaching",
    subtitle18: "Eyelash Extension Services",
    subtitle19: "Cosmetic Dentistry",
    subtitle20: "Personal Stylist and Image Consulting",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 1,
    category: "enterprise",
    image: Government,
    title: "Government",
    link: "/government",
    subtitle1: "Upskilling Programs",
    subtitle2: "e-Governance",
    subtitle3: "Licensing",
    subtitle4: "Tax management",

    popular: true,
    trending: false,
  },
  {
    id: 2,
    category: "enterprise",
    image: Corporation,
    title: "Corporations",
    link: "/corporation",
    subtitle1: "Hackathons",
    subtitle2: "Pitch Competitions",
    subtitle3: "Incubation Programs",
    subtitle4: "Accelerator Programs",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 3,
    category: "enterprise",
    image: NGO,
    title: "Foundations/NGOs",
    link: "/non-profit",
    subtitle1: "Program Management",
    subtitle2: "Event Management",
    subtitle3: "Hackathons",
    subtitle4: "Upskilling Programs",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 4,
    category: "enterprise",
    image: Religion,
    title: "Religious Bodies",
    link: "/religious-bodies",
    subtitle1: "Donor management",
    subtitle2: "Volunteer management",
    subtitle3: "Study Management",
    subtitle4: "Surveys",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 5,
    category: "consumer",
    image: Professional,
    title: "Professional Services",
    link: "/professional-services",
    subtitle1: "Legal Consulting",
    subtitle2: "Financial Planning",
    subtitle3: "Tax Preparation",
    subtitle4: "Accounting Services",
    subtitle5: "Business Consulting",
    subtitle6: "Human Resources Consulting",
    subtitle7: "Marketing Consulting",
    subtitle8: "Public Relations Services",
    subtitle9: "Risk Management Consulting",
    subtitle10: "Real Estate Consulting",
    subtitle11: "Recruitment Services",
    subtitle12: "Project Management",
    subtitle13: "Compliance Consulting",
    subtitle14: "Environmental Consulting",
    subtitle15: "Management Consulting",
    subtitle16: "Insurance Consulting",
    subtitle17: "Investment Advisory",
    subtitle18: "Intellectual Property Consulting",
    subtitle19: "Strategic Planning",
    subtitle20: "Organizational Development",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 6,
    category: "consumer",
    image: Creative,
    title: "Creative Services",
    link: "/creative-services",
    subtitle1: "Graphic Design",
    subtitle2: "Fashion Design",
    subtitle3: "Web Design",
    subtitle4: "Branding Services",
    subtitle5: "UX/UI Design",
    subtitle6: "Photography",
    subtitle7: "Videography",
    subtitle8: "Animation & Illustration",
    subtitle9: "SEO and Digital Marketing Consulting",
    subtitle10: "Copywriting",
    subtitle11: "Content Creation",
    subtitle12: "Social Media Management",
    subtitle13: "Advertising Design",
    subtitle14: "Interior Design",
    subtitle15: "Logo Design",
    subtitle16: "Art Direction",
    subtitle17: "Print Design",
    subtitle18: "Music Production",
    subtitle19: "Voiceover Services",
    subtitle20: "Podcast Production",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 7,
    category: "consumer",
    image: Home,
    title: "Trade Services",
    link: "/trade-services",
    subtitle1: "Plumbing Services",
    subtitle2: "Electrical Services",
    subtitle3: "Carpentry Services",
    subtitle4: "HVAC (Heating, Ventilation, and Air Conditioning) Services",
    subtitle5: "Roofing Services",
    subtitle6: "Landscaping and Lawn Care",
    subtitle7: "Painting Services",
    subtitle8: "Masonry Services",
    subtitle9: "Flooring Installation and Repair",
    subtitle10: "Auto Repair and Maintenance",
    subtitle11: "Welding and Metal Fabrication",
    subtitle12: "Appliance Repair Services",
    subtitle13: "Locksmith & Home Security Services",
    subtitle14: "Pest Control Services",
    subtitle15: "Removal & Waste Management",
    subtitle16: "Moving Services",
    subtitle17: "Tile, Drywall, Plaster Services",
    subtitle18: "Glass and Window Repair Services",
    subtitle19: "Handyman Services",
    subtitle20: "Cleaning and Janitorial Services",
    recommended: false,
    popular: true,
    trending: false,
  },
 
  {
    id: 9,
    category: "consumer",
    image: Event,
    title: "Event Services",
    link: "/event-services",
    subtitle1: "Event Planning",
    subtitle2: "Wedding Planning",
    subtitle3: "Catering Services",
    subtitle4: "DJ Services",
    subtitle5: "Live Band Services",
    subtitle6: "Photography Services",
    subtitle7: "Videography Services",
    subtitle8: "Florist Services",
    subtitle9: "Event Rentals",
    subtitle10: "Lighting and Sound Services",
    subtitle11: "Event Coordination",
    subtitle12: "Bartending Services",
    subtitle13: "Security Services",
    subtitle14: "Decoration Services",
    subtitle15: "Venue Booking",
    subtitle16: "Invitation Design",
    subtitle17: "Event Staffing",
    subtitle18: "Childcare Services",
    subtitle19: "Transportation Services",
    subtitle20: "Entertainment Booking",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 10,
    category: "consumer",
    image: Educational,
    title: "Educational Services",
    link: "/education",
    subtitle1: "Tutoring",
    subtitle2: "Test Preparation",
    subtitle3: "Language Lessons",
    subtitle4: "Music Lessons",
    subtitle5: "Art Lessons",
    subtitle6: "Dance Lessons",
    subtitle7: "Cooking Classes",
    subtitle8: "Coding Bootcamps",
    subtitle9: "Professional Development Workshops",
    subtitle10: "Corporate Training",
    subtitle11: "Public Speaking Coaching",
    subtitle12: "Writing Workshops",
    subtitle13: "STEM Education",
    subtitle14: "Early Childhood Education",
    subtitle15: "Special Education Services",
    subtitle16: "Study Skills Coaching",
    subtitle17: "College Admissions Counseling",
    subtitle18: "Career Coaching",
    subtitle19: "Online Courses",
    subtitle20: "Educational Consulting",
    recommended: false,
    popular: true,
    trending: false,
  },
  {
    id: 11,
    category: "consumer",
    image: Technical,
    title: "Technology Services",
    link: "/technology-services",
    subtitle1: "IT Support",
    subtitle2: "Software Development",
    subtitle3: "Web Development",
    subtitle4: "Mobile App Development",
    subtitle5: "Network Setup and Maintenance",
    subtitle6: "Cybersecurity Services",
    subtitle7: "Cloud Computing Services",
    subtitle8: "Data Analytics and Business Intelligence",
    subtitle9: "Database Management",
    subtitle10: "IT Consulting",
    subtitle11: "Technical Writing",
    subtitle12: "Website Hosting and Domain Services",
    subtitle13: "Tech Support Call Centers",
    subtitle14: "Hardware Repair",
    subtitle15: "IT Staffing and Recruitment",
    subtitle16: "Tech Training and Certification",
    subtitle17: "IoT Solutions",
    subtitle18: "AI and Machine Learning Development",
    subtitle19: "Blockchain Development",
    subtitle20: "ERP Implementation",
    recommended: false,
    popular: true,
    trending: false,
  },
];

export default AllCoursesData;
