const categorySubSection = {

    "Government": [
      "Licensing",
      "e-Governance",
      "Tax Management",
      "Upskilling Programs"
    ],
    "Corporations": [
      "Hackathons",
      "Pitch Competitions",
      "Incubation Programs",
      "Accelerator Programs",
      "Upskilling Programs"
    ],
    "Foundations/NGO's": [
      "Program Management",
      "Event Management",
      "Hackathons",
      "Incubation programs",
      "Upskilling Programs"
    ],
    "Religious Bodies": [
      "Donor management",
      "Volunteer management",
      "Study Management",
      "Surveys",
      "Events Management"
    ],

    "Professional Services": [
      "Legal Consulting",
      "Financial Planning",
      "Tax Preparation",
      "Accounting Services",
      "Business Consulting",
      "Human Resources Consulting",
      "Marketing Consulting",
      "Public Relations Services",
      "Risk Management Consulting",
      "Real Estate Consulting",
      "Recruitment Services",
      "Project Management",
      "Compliance Consulting",
      "Environmental Consulting",
      "Management Consulting",
      "Insurance Consulting",
      "Investment Advisory",
      "Intellectual Property Consulting",
      "Strategic Planning",
      "Organizational Development"
    ],
    "Creative Services": [
      "Graphic Design",
      "Logo Design",
      "Branding Services",
      "Web Design",
      "UI/UX Design",
      "Photography",
      "Videography",
      "Animation",
      "Illustration",
      "Copywriting",
      "Content Creation",
      "Social Media Management",
      "Advertising Design",
      "Interior Design",
      "Fashion Design",
      "Art Direction",
      "Print Design",
      "Music Production",
      "Voiceover Services",
      "Podcast Production",
    ],
    "Home Services": [
      "House Cleaning",
      "Carpet Cleaning",
      "Window Cleaning",
      "Plumbing Services",
      "Electrical Services",
      "Handyman Services",
      "Lawn Care",
      "Landscaping",
      "Pest Control",
      "HVAC Maintenance",
      "Pool Cleaning",
      "Gutter Cleaning",
      "Home Security Installation",
      "Painting Services",
      "Roofing Services",
      "Appliance Repair",
      "Moving Services",
      "Junk Removal",
      "Pressure Washing",
      "Home Organization",
    ],
    "Health and Wellness Services": [
      "Personal Training",
      "Nutrition Consulting",
      "Yoga Instruction",
      "Massage Therapy",
      "Chiropractic Services",
      "Acupuncture",
      "Physical Therapy",
      "Mental Health Counseling",
      "Life Coaching",
      "Meditation Instruction",
      "Pilates Instruction",
      "Aromatherapy",
      "Reflexology",
      "Hypnotherapy",
      "Weight Loss Coaching",
      "Sports Therapy",
      "Occupational Therapy",
      "Holistic Health Counseling",
      "Reiki Healing",
      "Wellness Retreats",
    ],
    "Educational Services": [
      "Tutoring",
      "Test Preparation",
      "Language Lessons",
      "Music Lessons",
      "Art Lessons",
      "Dance Lessons",
      "Cooking Classes",
      "Coding Bootcamps",
      "Professional Development Workshops",
      "Corporate Training",
      "Public Speaking Coaching",
      " Writing Workshops",
      "STEM Education",
      "Early Childhood Education",
      "Special Education Services",
      "Study Skills Coaching",
      "College Admissions Counseling",
      "Career Coaching",
      "Online Courses",
      "Educational Consulting",

    ],
    "Event Services": [
      "Event Planning",
      "Wedding Planning",
      "Catering Services",
      "DJ Services",
      "Live Band Services",
      "Photography Services",
      "Videography Services",
      "Florist Services",
      "Event Rentals",
      "Lighting and Sound Services",
      "Event Coordination",
      "Bartending Services",
      "Security Services",
      "Decoration Services",
      "Venue Booking",
      "Invitation Design",
      "Event Staffing",
      "Childcare Services",
      "Transportation Services",
      "Entertainment Booking",
    ],
    "Technical Services": [
      "IT Support",
      "Software Development",
      "Web Development",
      "Mobile App Development",
      "Network Setup and Maintenance",
      "Cybersecurity Services",
      "Cloud Computing Services",
      "Data Recovery Services",
      "Database Management",
      "IT Consulting",
      "Technical Writing",
      "Systems Integration",
      "Tech Support Call Centers",
      "Hardware Repair",
      "Managed IT Services",
      "IoT Solutions",
      "AI and Machine Learning Development",
      "Blockchain Development",
      "ERP Implementation",
    ],
    
  };
  
  export default categorySubSection;
  