const categorySubSection = {

    "Government": [
      "Licensing",
      "e-Governance",
      "Tax Management",
      "Upskilling Programs"
    ],
    "Corporations": [
      "Hackathons",
      "Pitch Competitions",
      "Incubation Programs",
      "Accelerator Programs",
      "Upskilling Programs"
    ],
    "Foundations/NGO's": [
      "Program Management",
      "Event Management",
      "Hackathons",
      "Incubation programs",
      "Upskilling Programs"
    ],
    "Religious Bodies": [
      "Donor management",
      "Volunteer management",
      "Study Management",
      "Surveys",
      "Events Management"
    ],

    "Professional Services": [
      "Legal Consulting",
      "Financial Planning",
      "Tax Preparation",
      "Accounting Services",
      "Business Consulting",
      "Human Resources Consulting",
      "Marketing Consulting",
      "Public Relations Services",
      "Risk Management Consulting",
      "Real Estate Consulting",
      "Recruitment Services",
      "Project Management",
      "Compliance Consulting",
      "Environmental Consulting",
      "Management Consulting",
      "Insurance Consulting",
      "Investment Advisory",
      "Intellectual Property Consulting",
      "Strategic Planning",
      "Organizational Development"
    ],
    "Creative Services": [
      "Graphic Design",
      "Logo Design",
      "Branding Services",
      "Web Design",
      "UI/UX Design",
      "Photography",
      "Videography",
      "Animation & Illustration",
      "SEO and Digital Marketing Consulting",
      "Copywriting",
      "Content Creation",
      "Social Media Management",
      "Advertising Design",
      "Interior Design",
      "Fashion Design",
      "Art Direction",
      "Print Design",
      "Music Production",
      "Voiceover Services",
      "Podcast Production",
    ],
    "Trade Services": [
      "Plumbing Services",
      "Electrical Services",
      "HVAC (Heating, Ventilation, and Air Conditioning) Service",
      "Carpentry Services",
      "Roofing Services",
      "Landscaping and Lawn Care",
      "Painting Services",
      "Masonry Services",
      "Flooring installations and repair",
      "Auto Repair and Maintenance",
      "Welding and Metal Fabrication",
      "Appliance Repair Services",
      "Locksmith & Home Security Services",
      "Pest Control Services",
      "Removal & Waste Management",
      "Moving Services",
      "Tile, Drywall, Plaster Services",
      "Glass and Window Repairs Services",
      "HandyMan Services",
      "Cleaning and Janitorial Services",
    ],
    "Personal Care Service": [
      "Hair Salon",
      "Barber Shop",
      "Nail Salon",
      "Spa and Wellness Center",
      "Massage Therapy",
      "Skincare Clinic",
      "Makeup Artist Services",
      "Personal Training and Fitness Coaching",
      "Yoga and Pilates Studio",
      "Weight Loss and Nutrition Counseling",
      "Chiropractic Services",
      "Mental Health Counseling",
      "Tattoo and Piercing Studio",
      "Aromatherapy Services",
      "Dental Hygiene Services",
      "Reflexology Services",
      "Life Coaching",
      "Eyelash Extension Services",
      "Cosmetic Dentistry",
      "Personal Stylist and Image Consulting",
    ],
    "Educational Services": [
      "Tutoring",
      "Test Preparation",
      "Language Lessons",
      "Music Lessons",
      "Art Lessons",
      "Dance Lessons",
      "Cooking Classes",
      "Coding Bootcamps",
      "Professional Development Workshops",
      "Corporate Training",
      "Public Speaking Coaching",
      " Writing Workshops",
      "STEM Education",
      "Early Childhood Education",
      "Special Education Services",
      "Study Skills Coaching",
      "College Admissions Counseling",
      "Career Coaching",
      "Online Courses",
      "Educational Consulting",

    ],
    "Event Services": [
      "Event Planning",
      "Wedding Planning",
      "Catering Services",
      "DJ Services",
      "Live Band Services",
      "Photography Services",
      "Videography Services",
      "Florist Services",
      "Event Rentals",
      "Lighting and Sound Services",
      "Event Coordination",
      "Bartending Services",
      "Security Services",
      "Decoration Services",
      "Venue Booking",
      "Invitation Design",
      "Event Staffing",
      "Childcare Services",
      "Transportation Services",
      "Entertainment Booking",
    ],
    "Technology Services": [
      "IT Support",
      "Software Development",
      "Web Development",
      "Mobile App Development",
      "Network Setup and Maintenance",
      "Cybersecurity Services",
      "Cloud Computing Services",
      "Data Analytics and Business Intelligence",
      "Database Management",
      "IT Consulting",
      "Technical Writing",
      "Website Hosting and Domain Services",
      "Tech Support Call Centers",
      "Hardware Repair",
      "IT Staffing and Recruitment",
      "Tech Training and Certification",
      "IoT Solutions",
      "AI and Machine Learning Development",
      "Blockchain Development",
      "ERP Implementation",
    ],
    
  };
  
  export default categorySubSection;
  